### ISSUE TITLE
使用方法

### ISSUE THREAD

**Issue by PHI6kai** [Stock-Fund/algorithm#2]
您好，看了您的代码，写的非常有逻辑和精致，想问一下怎么使用在数据上呢

**Comment by akeboshi1** [comment]
> 您好，看了您的代码，写的非常有逻辑和精致，想问一下怎么使用在数据上呢

这个是案例，内部使用了算法项目，将爬取的数据传入算法内部进行计算和判断
https://github.com/Stock-Fund/XCrawler

**Comment by PHI6kai** [comment]
> > 您好，看了您的代码，写的非常有逻辑和精致，想问一下怎么使用在数据上呢
> 
> 这个是案例，内部使用了算法项目，将爬取的数据传入算法内部进行计算和判断 https://github.com/Stock-Fund/XCrawler

您好，非常感谢您给的案例，我对于代码能力获益匪浅，但是没有发现可以使用您交易判断algorithm的接口，只是一些数据爬虫，想问一下关于交易判断的算法是如何使用的呢

**Comment by akeboshi1** [comment]
> > > 您好，看了您的代码，写的非常有逻辑和精致，想问一下怎么使用在数据上呢
> > 
> > 
> > 这个是案例，内部使用了算法项目，将爬取的数据传入算法内部进行计算和判断 https://github.com/Stock-Fund/XCrawler
> 
> 您好，非常感谢您给的案例，我对于代码能力获益匪浅，但是没有发现可以使用您交易判断algorithm的接口，只是一些数据爬虫，想问一下关于交易判断的算法是如何使用的呢

项目内有个stock_quantify_test.py文件，内部有引入算法项目和测试步骤，实际上这个算法项目相当于一个方法库，公开一些接口来判断传入股票数据的一些走势/信息，具体细节，你可以去看下。
